# -*- coding: utf-8 -*-
"""caracterporcaracterpython.ipynb

Automatically generated by Colaboratory.

"""

# leer una cadena carácter por carácter en Python 3: con y sin índice

cadena = "¡Hola, mundo!"

for caracter in cadena:
    print(caracter)