# -*- coding: utf-8 -*-
"""DiscursoPoliticoPython.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1_P7WAPPo_0KieL7PXk8pe2A5lYzdblet
"""

import random #se importa la librería de python random

lambetazo = ["Queridos", "Apreciados", "Distinguidos", "Honorables", "Estimados", "Respetados"]
marranos = ["compatriotas", "conciudadanos", "amigos", "coterraneos", "copartidarios", "electores"]
condiciones = ["en mi gobierno", "con su apoyo", "siendo elegido", "con su ayuda", "si me siguen", "durante mi mandato"]
compromiso = ["voy a derrotar", "vencere", "eliminare", "acabare", "luchare contra", "combatire"]
ilusion = ["la violencia y", "la delicuencia y", "la corrupcion y", "la inflacion y", "la pobreza y", "el desplazamiento"]
promesa = ["trabajare por", "garantizare", "protegere", "velare por", "promovere", "defendere"]
beneficio = ["la educacion", "el empleo", "la seguridad", "la paz", "la igualdad", "la salud"]

l1 = random.choice(lambetazo) #se utiliza la librería para seleccionar un elemento al azar de la lista
m1 = random.choice(marranos)
c1 = random.choice(condiciones)
co1 = random.choice(compromiso)
i1 = random.choice(ilusion)
p1 = random.choice(promesa)
b1 = random.choice(beneficio)

print("Mi Discurso politico es: " + l1 + " " + m1 + " " + c1 + " " + co1 + " " + i1 + " " + p1 + " " + b1) #se imprime el resultado