# -*- coding: utf-8 -*-
"""factorial.ipynb

Automatically generated by Colaboratory.

"""

# Imprimir los numeros de 1 hasta un numero natural n dado, cada uno
# con su respectivo factorial.

numero  = 5

def factorial(numero):
    if numero == 0:
        r = 1
    else:
        r = numero * fact(numero - 1)
    return r

vec = range(1,numero+1)
for i in vec:
  # print(i)
  print("Factorial: ", factorial(i))

#print(factorial(num))