# -*- coding: utf-8 -*-
"""while1python.ipynb

Automatically generated by Colaboratory.

"""

#While N numbers

n = int(input())

while n > 0:

    n -= 1

    if n == 2:

        continue

    print(n)

print('Loop ended.')